export const wordsData = [
    "apple", "table", "green", "orange", "chair", "happy", "smile", "mouse", "keyboard", "melon",
    "grape", "music", "sunny", "cloud", "paper", "pencil", "river", "forest", "phone", "guitar",
    "email", "radio", "pizza", "bread", "juice", "watch", "clock", "coffee", "cookie", "beach",
    "sugar", "spoon", "plate", "knife", "mouse", "horse", "tiger", "eagle", "ocean", "mountain",
    "snake", "dolphin", "planet", "rocket", "queen", "jelly", "peanut", "banana", "mango", "lemon",
    "cherry", "water", "drink", "candy", "dress", "shirt", "glove", "socks", "shoes", "heart",
    "sleep", "dream", "dance", "phone", "radio", "paper", "pen", "light", "cloud", "stone",
    "bread", "coffee", "beach", "sugar", "spoon", "plate", "knife", "teeth", "mouth", "elephant",
    "zebra", "butterfly", "giraffe", "sunflower", "airplane", "penguin", "koala", "kangaroo", "giraffe",
    "watermelon", "pineapple", "cucumber", "broccoli", "carrot", "tomato", "waterfall", "fireplace", "rainbow",
    "waterfall", "volcano", "bicycle", "motorcycle", "umbrella", "compass", "telescope", "microscope", "glasses", "butter", "blanket", "flute", "shampoo", "piano", "cheese", "breeze", "mirror", "trouble", "honey",
    "island", "tulip", "cricket", "diamond", "bubble", "cradle", "velvet", "whisper", "shadow", "silver",
    "waffle", "crystal", "feather", "garden", "oasis", "parrot", "quartz", "raindrop", "sapphire", "tricycle",
    "violin", "willow", "zeppelin", "acorn", "bonfire", "cactus", "dragonfly", "fern", "gazelle", "hummingbird",
    "jigsaw", "kaleidoscope", "lighthouse", "magnolia", "noodle", "octopus", "parachute", "quokka", "raccoon", "starfish",
    "tangerine", "umbrella", "violet", "whale", "xylophone", "yacht", "zebra", "albatross", "broccoli", "caramel",
    "dandelion", "eclipse", "firefly", "goblin", "horizon", "illusion", "jungle", "kangaroo", "labyrinth", "marmalade",
    "nymph", "orchid", "peacock", "quill", "rainbow", "seahorse", "tornado", "unicorn", "volcano", "waterfall",
    "xenon", "yeti", "zephyr"
  ];

  export const alphabetData = [
    { letter: "a", active: 'active' },
    { letter: "b", active: 'active' },
    { letter: "c", active: 'active' },
    { letter: "d", active: 'active' },
    { letter: "e", active: 'active' },
    { letter: "f", active: 'active' },
    { letter: "g", active: 'active' },
    { letter: "h", active: 'active' },
    { letter: "i", active: 'active' },
    { letter: "j", active: 'active' },
    { letter: "k", active: 'active' },
    { letter: "l", active: 'active' },
    { letter: "m", active: 'active' },
    { letter: "n", active: 'active' },
    { letter: "o", active: 'active' },
    { letter: "p", active: 'active' },
    { letter: "q", active: 'active' },
    { letter: "r", active: 'active' },
    { letter: "s", active: 'active' },
    { letter: "t", active: 'active' },
    { letter: "u", active: 'active' },
    { letter: "v", active: 'active' },
    { letter: "w", active: 'active' },
    { letter: "x", active: 'active' },
    { letter: "y", active: 'active' },
    { letter: "z", active: 'active' },
  ];
  